version: "3.9"

services:
  api:
    build:
      dockerfile: Dockerfile.prod
    image: portfolio-api:prod
    container_name: portfolio-api-prod
  ui:
    build:
      dockerfile: Dockerfile.prod
    image: portfolio-ui:prod
    container_name: portfolio-ui-prod
    ports:
      - "80:80"
    env_file:
      - .env.prod