version: "3.9"

services:
  api:
    build:
      dockerfile: Dockerfile.prod
    image: portfolio-api:prod
    container_name: portfolio-api-prod
  ui:
    build:
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_API_HOST=d2kijccpv783lg.cloudfront.net
        - REACT_APP_API_PORT=443
    image: portfolio-ui:prod
    container_name: portfolio-ui-prod
    ports:
      - "80:80"