name: CD

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [trigger-deploy]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      # - name: Run deploy script
      #   run: ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} < deploy-to-aws.sh
